### PR TITLE
Fix build error and use xml2-config to get flag

### PR DESCRIPTION
**Pull request by zodf0055980**
In my system, it caused compile error.
```
cc -O3 -funroll-loops -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -Wno-variadic-macros -Wall -Wextra -Wpointer-arith -I include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -D_FORTIFY_SOURCE=2 -Iinclude -fno-move-loop-invariants -fdisable-tree-cunrolli `xml2-config --libs` -O3 -fno-unroll-loops -c src/afl-performance.c -o src/afl-performance.o
cc1: note: disable pass tree-cunrolli for functions in the range of [0, 4294967295]
In file included from include/afl-fuzz.h:82,
                 from src/afl-performance.c:23:
include/parse.h:2:10: fatal error: libxml/parser.h: 沒有此一檔案或目錄
    2 | #include <libxml/parser.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```
I think you miss libxml2 flag when compile afl-performance.

And in Libxml2 [doc](http://xmlsoft.org/FAQ.html), use xml2-config to get flag is more better.

### CODE REVIEW

**Comment by zodf0055980** [comment]
But you didn't modify afl-performance.c, I think you need to check library using in header file

**Comment by a4865g** [comment]
Oh, Thanks for report！

I forgot to add some settings for libxml2...

I have completed the setup information in the README, please try again！

**Comment by zodf0055980** [comment]
This problem is for afl-performance.c include afl-fuzz.h
https://github.com/a4865g/WuLearn-fuzz/blob/fc2125f4cc3501eb6bf1f282f1b84e6593236c60/src/afl-performance.c#L23

And afl-fuzz.h include parse.h
https://github.com/a4865g/WuLearn-fuzz/blob/fc2125f4cc3501eb6bf1f282f1b84e6593236c60/include/afl-fuzz.h#L82

And parse.h include libxml2
https://github.com/a4865g/WuLearn-fuzz/blob/fc2125f4cc3501eb6bf1f282f1b84e6593236c60/include/parse.h#L2

But afl-performance never use function in parse.c, this should not include it.

However, directly move library director may cause a problem in program which uses libxml2 , I don't think this is good way to fix.

**Comment by a4865g** [comment]
Oops! 
It is exactly as you say. I did not notice this issue.
Thanks again for your clarification and PR!

**Pull request merged**
